name: Deploy to gh pages

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn prettier
      - name: Run linting
        run: yarn lint
      - name: Deploy to gh pages
        run: yarn run deploy
